### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by SANOR9000** [necauqua/chiseled-me#1]
Hi, so the only mods i have are Ice and Fire: Dragons in a whole new light!", "Mowzie's Mobs" and the library "LLibrary", and the forge version "1.10.2-forge1.10.2-12.18.3.2185 (the recomended version rn). Nothing bad with the 3 mods, but when i install this mod the game crashes, with this exit code. (js i just pasted it i did not edited anything)

<details>
<summary>the crash</summary>
<p>

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Chiseled Me ASM (Chiseled-Me-1.0.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 15/02/19 21:16
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78467_g(F)V @244: aload_2
  Reason:
    Type float (current frame, locals[2]) is not assignable to reference type
  Current Frame:
    bci: @244
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, float, 'net/minecraft/entity/Entity', float, double, double_2nd, double, double_2nd, double, double_2nd }
    stack: { float }
  Bytecode:
    0x0000000: 2ab4 00b3 b601 474e 2db6 02f7 572d 23b8
    0x0000010: 02fb 452d 23b8 02fe 3804 2db4 0301 2db4
    0x0000020: 0304 2db4 0301 6723 8d6b 6339 052d b403
    0x0000030: 072d b403 0a2d b403 0767 238d 6b63 1704
    0x0000040: 8d63 3907 2db4 030d 2db4 0310 2db4 030d
    0x0000050: 6723 8d6b 6339 092d c102 6299 0088 2dc0
    0x0000060: 0262 b603 1399 007e 1704 8d0f 6390 3804
    0x0000070: 0b13 0314 0bb8 02ef 2ab4 00b3 b401 64b4
    0x0000080: 0317 9a02 2abb 001c 592d b701 8e3a 0b2a
    0x0000090: b400 b3b4 018c 190b b603 1b3a 0c2a b400
    0x00000a0: b3b4 018c 190b 190c 2db8 031f 2db4 0322
    0x00000b0: 2db4 0325 2db4 0322 6623 6a62 1303 2662
    0x00000c0: 0b13 0327 0bb8 02bb 2db4 032a 2db4 032d
    0x00000d0: 2db4 032a 6623 6a62 1303 270b 0bb8 02bb
    0x00000e0: a701 cc2a b400 b3b4 0164 b403 309e 01b5
    0x00000f0: 2ab4 0093 2c23 b803 352a b400 9366 236a
    0x0000100: 628d 248d 6b39 0d2a b400 b3b4 0164 b403
    0x0000110: 1799 000f 0b0b 180d 7790 b802 efa7 0182
    0x0000120: 2db4 0325 380f 2db4 032d 3810 2ab4 00b3
    0x0000130: b401 64b4 0330 05a0 000b 1710 1303 2662
    0x0000140: 3810 170f 1303 366a b802 c276 1710 1303
    0x0000150: 366a b802 e66a 8d18 0d6b 3911 170f 1303
    0x0000160: 366a b802 e617 1013 0336 6ab8 02e6 6a8d
    0x0000170: 180d 6b39 1317 1013 0336 6ab8 02c2 768d
    0x0000180: 180d 6b39 1503 3617 1517 1008 a200 bf15
    0x0000190: 1704 7e05 6804 6486 3818 1517 047a 047e
    0x00001a0: 0568 0464 8638 1915 1705 7a04 7e05 6804
    0x00001b0: 6486 381a 1718 1301 9924 6a6a 3818 1719
    0x00001c0: 1301 9924 6a6a 3819 171a 1301 9924 6a6a
    0x00001d0: 381a 2ab4 00b3 b401 8cbb 01f6 5918 0517
    0x00001e0: 188d 6318 0717 198d 6318 0917 1a8d 63b7
    0x00001f0: 0339 bb01 f659 1805 1811 6717 188d 6317
    0x0000200: 1a8d 6318 0718 1567 1719 8d63 1809 1813
    0x0000210: 6717 1a8d 63b7 0339 b603 3c3a 1b19 1bc6
    0x0000220: 0026 191b b401 fcbb 01f6 5918 0518 0718
    0x0000230: 09b7 0339 b602 0039 1c18 1c18 0d98 9c00
    0x0000240: 0718 1c39 0d84 1701 a7ff 402a b400 b3b4
    0x0000250: 0164 b403 3005 a000 0c13 0326 0b0c 0bb8
    0x0000260: 02bb 2db4 032d 1710 660c 0b0b b802 bb2d
    0x0000270: b403 2517 0f66 0b0c 0bb8 02bb 0b0b 180d
    0x0000280: 7790 b802 ef17 0f2d b403 2566 0b0c 0bb8
    0x0000290: 02bb 1710 2db4 032d 660c 0b0b b802 bba7
    0x00002a0: 000d 0b0b 1301 7224 6ab8 02ef 2ab4 00b3
    0x00002b0: b401 64b4 0317 9a00 a12d b403 222d b403
    0x00002c0: 252d b403 2266 236a 6213 0326 6238 0b2d
    0x00002d0: b403 2a2d b403 2d2d b403 2a66 236a 6238
    0x00002e0: 0c0b 380f 2dc1 033e 9900 222d c003 3e3a
    0x00002f0: 1019 10b4 0341 1910 b403 4419 10b4 0341
    0x0000300: 6623 6a62 1303 2662 380b 2ab4 00b3 b401
    0x0000310: 8c2d 23b8 029c 3a10 bb00 1559 2a2d 1910
    0x0000320: 238d 170b 170c 170f b703 473a 1eb2 034d
    0x0000330: 191e b603 5357 191e b603 560b 0b0c b802
    0x0000340: bb19 1eb6 0359 0c0b 0bb8 02bb 191e b603
    0x0000350: 5c0b 0c0b b802 bb0b 1704 760b b802 ef2d
    0x0000360: b403 012d b403 042d b403 0167 238d 6b63
    0x0000370: 3905 2db4 0307 2db4 030a 2db4 0307 6723
    0x0000380: 8d6b 6317 048d 6339 072d b403 0d2d b403
    0x0000390: 102d b403 0d67 238d 6b63 3909 2a2a b400
    0x00003a0: b3b4 01c0 1805 1807 1809 23b6 0360 b503
    0x00003b0: 62b1                                   
  Stackmap Table:
    full_frame(@227,{Object[#2],Float,Float,Object[#483],Float,Double,Double,Double},{})
    append_frame(@288,Top,Top,Double)
    append_frame(@322,Float,Float)
    full_frame(@392,{Object[#2],Float,Float,Object[#483],Float,Double,Double,Double,Top,Top,Double,Float,Float,Double,Double,Double,Integer},{})
    full_frame(@581,{Object[#2],Float,Float,Object[#483],Float,Double,Double,Double,Top,Top,Double,Float,Float,Double,Double,Double,Integer,Float,Float,Float,Object[#36]},{})
    full_frame(@587,{Object[#2],Float,Float,Object[#483],Float,Double,Double,Double,Top,Top,Double,Float,Float,Double,Double,Double,Integer},{})
    same_frame(@610)
    full_frame(@671,{Object[#2],Float,Float,Object[#483],Float,Double,Double,Double,Top,Top,Double},{})
    chop_frame(@674,3)
    same_frame(@684)
    full_frame(@778,{Object[#2],Float,Float,Object[#483],Float,Double,Double,Double,Float,Float,Top,Top,Float},{})
    full_frame(@855,{Object[#2],Float,Float,Object[#483],Float,Double,Double,Double},{})

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 954460656 bytes (910 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	chiseled_me{1.0} [Chiseled Me] (Chiseled-Me-1.0.jar) 
	UCH	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.10.2.jar) 
	UCH	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1.jar) 
	UCH	mowziesmobs{1.3.2} [Mowzie's Mobs] (mowziesmobs-1.3.2.jar) 
	Loaded coremods (and transformers): 
Chiseled Me ASM (Chiseled-Me-1.0.jar)
  necauqua.mods.cm.asm.Plugin
llibrary (llibrary-1.7.7-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13542 Compatibility Profile Context 25.20.14011.5005' Renderer: 'Radeon(TM) RX 460 Graphics'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Radeon(TM) RX 460 Graphics GL version 4.5.13542 Compatibility Profile Context 25.20.14011.5005, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/! Â§6Â§lHYPIXELÂ§4Â§lZOMBIES.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-6600K APU with Radeon(tm) HD Graphics
```

</p>
</details>

**Comment by necauqua** [comment]
Hello, and thanks for your input.
I am right now in process of reworking and fixing the ASM (bytecode manipulation stuff) and also exactly this bug is most likely already fixed because I remember something like that.
Or maybe some of your other mods touch the same piece of bytecode, this is also a possibility.

Anyway, you'll have to wait (at least a week or two) for the update and then check again, because the old code from 2016 is broken in so many places and my current version (not yet pushed to GitHub) is very different.

P.S. Also please use [spoilers](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f) for crashlogs, we need to spread the fact that GitHub's markdown has those.

**Comment by necauqua** [comment]
Well, I've updated the mod, you can test it now with the 1.1.0 version.

**Comment by necauqua** [comment]
Closing because: not enough info, old code bug, no further input
