### ISSUE TITLE
Error on server(Linux)

### ISSUE THREAD

**Issue by rich1051414** [necauqua/Chiseled-Me#15]
[12:17:55] [main/WARN] [LaunchWrapper/]: Tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker has already been visited -- skipping
[12:17:55] [main/DEBUG] [mixin/]: Adding new mixin transformer proxy #3
[12:17:55] [main/DEBUG] [mixin/]: Preparing mixins for MixinEnvironment[DEFAULT]
[12:17:55] [main/DEBUG] [mixin/]: Selecting config mixins.forgeessentials.json
[12:17:55] [main/DEBUG] [mixin/]: Preparing mixins.forgeessentials.json (10)
[12:17:55] [main/DEBUG] [mixin/]: Rebuilding transformer delegation list:
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Excluding: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Excluding: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    com.forgeessentials.core.preloader.EventTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.AccessTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Excluding: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
[12:17:55] [main/DEBUG] [mixin/]:   Adding:    $wrapper.necauqua.mods.cm.asm.Plugin
[12:17:55] [main/DEBUG] [mixin/]:   Excluding: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
[12:17:55] [main/DEBUG] [mixin/]:   Excluding: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
[12:17:55] [main/DEBUG] [mixin/]: Transformer delegation list created with 10 entries
[12:17:55] [main/DEBUG] [mixin/]: Found name transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/BlockPortal to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/BlockFire to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/BlockEndPortal to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/command/CommandHandler to metadata cache
[12:17:55] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.entity.Entity
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_70071_h_()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityMotion}: func_70091_d(DDD)V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after all LDC 0.05>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before DSTORE 3 at 3>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_145775_I()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before ALOAD 8>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after INVOKEVIRTUAL net/minecraft/block/Block.func_180634_a(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/entity/Entity;)V>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityMotion}: func_174808_Z()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_70094_T()Z
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 0.1>
[12:17:55] [main/DEBUG] [Chiseled Me/]: One of patches from net.minecraft.entity.Entity wasn't applied but ignoring because it's marked as optional (eg. @SideOnly)
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/Entity to metadata cache
[12:17:55] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.entity.player.EntityPlayer
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_184808_cD()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before FLOAD 1>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_70636_d()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before IFEQ at 5>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <replace all DCONST_1>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 0.5>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {itemFixes}: func_146097_a(Lnet/minecraft/item/ItemStack;ZZ)Lnet/minecraft/entity/item/EntityItem;
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 0.30000001192092896>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {playerEyeHeight}: func_70047_e()F
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before FRETURN>
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/player/EntityPlayer to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/player/EntityPlayerMP to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/item/crafting/CraftingManager to metadata cache
[12:17:55] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.network.NetHandlerPlayServer
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {serverMotionFixes}: func_147347_a(Lnet/minecraft/network/play/client/CPacketPlayer;)V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before ALOAD 2>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after DLOAD 19 at 4>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after DLOAD 21 at 5>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after DLOAD 23 at 4>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after all LDC 0.0625>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {reachDistance}: func_147340_a(Lnet/minecraft/network/play/client/CPacketUseEntity;)V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after DLOAD 5>
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/network/NetHandlerPlayServer to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/common/DimensionManager to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fe/event/world/FireEvent$Destroy to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fe/event/world/FireEvent$Spread to metadata cache
[12:17:55] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.world.World
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {reachDistance}: func_147447_a(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;ZZZ)Lnet/minecraft/util/math/RayTraceResult;
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <replace ARETURN at 3>
[12:17:55] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.entity.Entity
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_70071_h_()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityMotion}: func_70091_d(DDD)V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after all LDC 0.05>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before DSTORE 3 at 3>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_145775_I()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before ALOAD 8>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after INVOKEVIRTUAL net/minecraft/block/Block.func_180634_a(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/entity/Entity;)V>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityMotion}: func_174808_Z()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_70094_T()Z
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 0.1>
[12:17:55] [main/DEBUG] [Chiseled Me/]: One of patches from net.minecraft.entity.Entity wasn't applied but ignoring because it's marked as optional (eg. @SideOnly)
[12:17:55] [main/DEBUG] [mixin/]: Mixing entity.MixinEntity from mixins.forgeessentials.json into net.minecraft.entity.Entity
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/common/MinecraftForge to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fe/event/world/PressurePlateEvent to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/event/entity/EntityEvent to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/eventhandler/Event to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/eventhandler/EventBus to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for java/util/List to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for java/util/ArrayList to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for java/util/AbstractList to metadata cache
[12:17:55] [main/TRACE] [mixin/]: Added class metadata for java/util/AbstractCollection to metadata cache
[12:17:55] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.entity.player.EntityPlayer
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_184808_cD()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before FLOAD 1>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityCollisions}: func_70636_d()V
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before IFEQ at 5>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <replace all DCONST_1>
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 0.5>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {itemFixes}: func_146097_a(Lnet/minecraft/item/ItemStack;ZZ)Lnet/minecraft/entity/item/EntityItem;
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 0.30000001192092896>
[12:17:55] [main/DEBUG] [Chiseled Me/]:  - Patching method with {playerEyeHeight}: func_70047_e()F
[12:17:55] [main/TRACE] [Chiseled Me/]:    * Applying <insert before FRETURN>
[12:17:56] [main/DEBUG] [mixin/]: Mixing entity.player.MixinEntityPlayer from mixins.forgeessentials.json into net.minecraft.entity.player.EntityPlayer
[12:17:56] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.entity.EntityLivingBase
[12:17:56] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityMotion}: func_70612_e(FF)V
[12:17:56] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 4.0>
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/EntityLivingBase to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/player/PlayerCapabilities to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/server/permission/PermissionAPI to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for java/lang/String to metadata cache
[12:17:56] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.entity.EntityLivingBase
[12:17:56] [main/DEBUG] [Chiseled Me/]:  - Patching method with {entityMotion}: func_70612_e(FF)V
[12:17:56] [main/TRACE] [Chiseled Me/]:    * Applying <insert after LDC 4.0>
[12:17:56] [main/DEBUG] [mixin/]: Mixing command.MixinCommandHandler from mixins.forgeessentials.json into net.minecraft.command.CommandHandler
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for com/forgeessentials/core/misc/PermissionManager to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/event/CommandEvent to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/util/text/TextComponentTranslation to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/util/text/TextComponentBase to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/command/CommandException to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/command/WrongUsageException to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for java/lang/Exception to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for java/lang/Throwable to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/command/SyntaxErrorException to metadata cache
[12:17:56] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[12:17:56] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.entity.item.EntityItem
[12:17:56] [main/DEBUG] [Chiseled Me/]:  - Patching method with {itemFixes}: func_85054_d()V
[12:17:56] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:56] [main/TRACE] [Chiseled Me/]:    * Applying <insert after all LDC 0.5>
[12:17:56] [main/DEBUG] [mixin/]: Mixing block.MixinBlockFire from mixins.forgeessentials.json into net.minecraft.block.BlockFire
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/Block to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/registry/IForgeRegistryEntry$Impl to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fe/event/world/FireEvent to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/event/world/BlockEvent to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for org/spongepowered/asm/mixin/injection/callback/CallbackInfo to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/util/EnumFacing to metadata cache
[12:17:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/util/math/BlockPos to metadata cache
[12:17:57] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.world.World
[12:17:57] [main/DEBUG] [Chiseled Me/]:  - Patching method with {reachDistance}: func_147447_a(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;ZZZ)Lnet/minecraft/util/math/RayTraceResult;
[12:17:57] [main/TRACE] [Chiseled Me/]:    * Applying <replace ARETURN at 3>
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/world/World to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/registry/IForgeRegistryEntry to metadata cache
[12:17:57] [main/DEBUG] [mixin/]: Mixing block.MixinBlockPortal from mixins.forgeessentials.json into net.minecraft.block.BlockPortal
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/BlockBreakable to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/util/math/Vec3i to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for java/lang/Comparable to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fe/event/entity/EntityPortalEvent to metadata cache
[12:17:57] [main/DEBUG] [mixin/]: Mixing block.MixinBlockEndPortal from mixins.forgeessentials.json into net.minecraft.block.BlockEndPortal
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/BlockContainer to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/state/IBlockState to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/state/IBlockBehaviors to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/state/IBlockProperties to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/util/math/AxisAlignedBB to metadata cache
[12:17:57] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/block/ITileEntityProvider to metadata cache
[12:17:57] [main/DEBUG] [Chiseled Me/]: Patching class: net.minecraft.tileentity.TileEntityBeacon
[12:17:57] [main/DEBUG] [Chiseled Me/]:   - Adding field: $cm_baseColor(Lnet/minecraft/item/EnumDyeColor;)
[12:17:57] [main/DEBUG] [Chiseled Me/]:  - Patching method with {beaconBaseColor}: <init>()V
[12:17:57] [main/TRACE] [Chiseled Me/]:    * Applying <insert after ALOAD 0 at 2>
[12:17:57] [main/DEBUG] [Chiseled Me/]:  - Patching method with {beaconBaseColor}: func_146003_y()V
[12:17:57] [main/TRACE] [Chiseled Me/]:    * Applying <replace GETSTATIC net/minecraft/item/EnumDyeColor.WHITE Lnet/minecraft/item/EnumDyeColor;>
[12:17:57] [main/DEBUG] [Chiseled Me/]:  - Patching method with {beaconBaseColor}: func_145839_a(Lnet/minecraft/nbt/NBTTagCompound;)V
[12:17:57] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:57] [main/DEBUG] [Chiseled Me/]:  - Patching method with {beaconBaseColor}: func_189515_b(Lnet/minecraft/nbt/NBTTagCompound;)Lnet/minecraft/nbt/NBTTagCompound;
[12:17:57] [main/TRACE] [Chiseled Me/]:    * Applying <insert after method begin>
[12:17:57] [main/DEBUG] [mixin/]: Mixing entity.player.MixinEntityPlayerMP from mixins.forgeessentials.json into net.minecraft.entity.player.EntityPlayerMP
[12:17:58] [main/DEBUG] [mixin/]: Mixing item.crafting.MixinCraftingManager from mixins.forgeessentials.json into net.minecraft.item.crafting.CraftingManager
[12:17:58] [main/TRACE] [mixin/]: Added class metadata for com/forgeessentials/protection/ModuleProtection to metadata cache
[12:17:58] [main/TRACE] [mixin/]: Added class metadata for java/util/Iterator to metadata cache
[12:17:58] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/item/crafting/IRecipe to metadata cache
[12:17:58] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.10.2-12.18.3.2477-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.10.2-12.18.3.2477-universal.jar:?]
Caused by: java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    net/minecraft/entity/Entity.func_145775_I()V @225: athrow
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @225
    flags: { }
    locals: { 'net/minecraft/entity/Entity', 'net/minecraft/util/math/AxisAlignedBB', 'net/minecraft/util/math/BlockPos$PooledMutableBlockPos', 'net/minecraft/util/math/BlockPos$PooledMutableBlockPos', 'net/minecraft/util/math/BlockPos$PooledMutableBlockPos', integer, integer, integer, 'net/minecraft/block/state/IBlockState' }
    stack: { }
  Bytecode:
    0x0000000: 2ab6 0173 4c2b b401 7814 030d 632b b401
    0x0000010: 7b14 030d 632b b401 7e14 030d 63b8 0372
    0x0000020: 4d2b b403 6214 030d 672b b403 7514 030d
    0x0000030: 672b b403 6714 030d 67b8 0372 4eb8 0379
    0x0000040: 3a04 2ab4 00f3 2c2d b603 7d99 00a3 2cb6
    0x0000050: 0380 3605 1505 2db6 0380 a300 942c b603
    0x0000060: 8336 0615 062d b603 83a3 007f 2cb6 0386
    0x0000070: 3607 1507 2db6 0386 a300 6a19 0415 0515
    0x0000080: 0615 07b6 038a 572a b400 f319 04b6 02a1
    0x0000090: 3a08 2a19 0819 04b8 038e 9a00 1619 08b9
    0x00000a0: 02b5 0100 2ab4 00f3 1904 1908 2ab6 0392
    0x00000b0: a700 2c3a 0919 0913 0394 b802 fa3a 0a19
    0x00000c0: 0a13 0396 b603 003a 0b19 0b19 0419 08b8
    0x00000d0: 039c bb03 0659 190a b703 09bf 0000 0000
    0x00000e0: 00bf 8406 01a7 ff7e 8405 01a7 ff69 2cb6
    0x00000f0: 039f 2db6 039f 1904 b603 9fb1          
  Exception Handler Table:
    bci [146, 176] => handler: 179
  Stackmap Table:
    full_frame(@84,{Object[#2],Object[#373],Object[#22],Object[#22],Object[#22],Integer},{})
    append_frame(@99,Integer)
    append_frame(@176,Integer,Object[#675])
    same_locals_1_stack_item_frame(@179,Object[#596])
    same_frame(@220)
    chop_frame(@226,1)
    chop_frame(@232,1)
    chop_frame(@238,2)

	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_45]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_45]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_45]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_45]
	at net.minecraft.world.biome.Biome$SpawnListEntry.<init>(Biome.java:640) ~[aiq$c.class:?]
	at net.minecraft.world.biome.Biome.<init>(Biome.java:122) ~[aiq.class:?]
	at net.minecraft.world.biome.BiomeOcean.<init>(SourceFile:10) ~[ajj.class:?]
	at net.minecraft.world.biome.Biome.func_185358_q(Biome.java:474) ~[aiq.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:545) ~[kq.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1403) ~[MinecraftServer.class:?]
	... 12 more

**Comment by necauqua** [comment]
Looks like my mod is also incompatible with Mixin(or whatever mod which uses it to modify Entity class)

**Comment by rich1051414** [comment]
Yes, turned out to be Forge Essentials. Unfortunate.
