### ISSUE TITLE
Crash report plz help

### ISSUE THREAD

**Issue by matthias7890** [necauqua/chiseled-me#26]
When I try to use chiseled me with 1.12.2 and then pressing play it says forge is loading some mods and then the game crashes. 

i think its just chiseled me mod here take a look at the crash report..
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 1/7/20 1:52 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@495afaf5 from coremod Chiseled Me ASM
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 16 more
Caused by: java.lang.IllegalStateException: Coremod failed!
Some patches were not applied to class EntityRenderer:
  transformer 'cameraView':
    method func_78479_a(FI)V:
      - <insert before INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>
      - <insert after INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>

	at dev.necauqua.mods.cm.asm.dsl.ASM.checkMisses(ASM.java:182)
	at dev.necauqua.mods.cm.asm.dsl.ASM.doTransform(ASM.java:129)
	at dev.necauqua.mods.cm.asm.Plugin.transform(Plugin.java:40)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 497325632 bytes (474 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                               | Signature                                |
	|:----- |:-------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| LC    | minecraft      | 1.12.2       | minecraft.jar                        | None                                     |
	| LC    | mcp            | 9.42         | minecraft.jar                        | None                                     |
	| LC    | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar        | None                                     |
	| LC    | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar        | None                                     |
	| LC    | securitycraft  | v1.8.14.1    | [1.12.2]+SecurityCraft+v1.8.14.1.jar | None                                     |
	| LC    | artemislib     | 1.0.6        | ArtemisLib-1.12.2-v1.0.6.jar         | None                                     |
	| LC    | cdm            | 0.4.1        | cdm-0.4.1-mc1.12.2.jar               | None                                     |
	| LC    | bubble_burst   | 3.1          | BubbleBurst-3.1.jar                  | None                                     |
	| LC    | cfm            | 6.3.0        | cfm-6.3.0-mc1.12.2.jar               | None                                     |
	| LC    | chiseled_me    | 2.0.0.1      | chiseled-me-1.12.2-2.0.0.1.jar       | c677c954974252994736eb15e855e1e6fc5a2e62 |
	| LC    | chiselsandbits | 14.33        | chiselsandbits-14.33.jar             | None                                     |
	| LC    | dragonmounts   | 1.12.2-1.6.3 | DragonMounts2-1.12.2-1.6.3.jar       | None                                     |
	| LC    | ichunutil      | 7.2.2        | iChunUtil-1.12.2-7.2.2.jar           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | resize         | 2.0          | Resizing+Potion-r2.1.jar             | None                                     |

	Loaded coremods (and transformers): 
Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1.jar)
  dev.necauqua.mods.cm.asm.Plugin
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.36.19' Renderer: 'Intel Iris Pro OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.2
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.36.19, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
Please reply on how to fix this
Thank you!

**Comment by matthias7890** [comment]
nevermind

**Comment by necauqua** [comment]
Well you can close the issue if it was opened by a mistake.

However, all of the transformer crashes and especially ones related to mod compat have the highest priority to be fixed in the future.
