### ISSUE TITLE
i can't play minecraft with this mod (version 1.12.2)

### ISSUE THREAD

**Issue by Zuzusuzu** [necauqua/chiseled-me#44]
When I try to use this mod with mod *X* (and/or by doing some set of actions), the game crashes. 

If you know exactly with what mod *X* this mod crashed, please check that it was not already reported.

**Additional information:**
- crashlog file or gist: *required*
- `fml-latest.log` file: *highly recommended to provide*

**Comment by necauqua** [comment]
Well, I need at least some information, without elaboration your issue is useless.
Anyway, try to update Forge first please

**Comment by 253488655422** [comment]
<details>
<summary>crashlog</summary>

```
[09:17:31] [main/WARN] [mixin]: Error loading class: net/minecraft/client/renderer/EntityRenderer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:31] [main/WARN] [mixin]: @Mixin target net.minecraft.client.renderer.EntityRenderer was not found mixins.render.replaymod.json:Mixin_ChromaKeyForceSky
[09:17:31] [main/WARN] [mixin]: Error loading class: net/minecraft/client/renderer/EntityRenderer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:31] [main/WARN] [mixin]: @Mixin target net.minecraft.client.renderer.EntityRenderer was not found mixins.render.replaymod.json:Mixin_CubicRotation
[09:17:31] [main/WARN] [mixin]: Error loading class: net/minecraft/client/renderer/EntityRenderer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:31] [main/WARN] [mixin]: @Mixin target net.minecraft.client.renderer.EntityRenderer was not found mixins.render.replaymod.json:MixinCamera
[09:17:31] [main/WARN] [mixin]: Error loading class: net/minecraft/client/renderer/EntityRenderer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:31] [main/WARN] [mixin]: @Mixin target net.minecraft.client.renderer.EntityRenderer was not found mixins.render.replaymod.json:MixinEntityRenderer
[09:17:31] [main/WARN] [mixin]: Error loading class: net/minecraft/client/renderer/WorldRenderer$LocalRenderInformationContainer (java.lang.ClassNotFoundException: The specified class 'net.minecraft.client.renderer.WorldRenderer$LocalRenderInformationContainer' was not found)
[09:17:31] [main/WARN] [mixin]: @Mixin target net.minecraft.client.renderer.WorldRenderer$LocalRenderInformationContainer was not found mixins.render.blend.replaymod.json:ContainerLocalRenderInformationAccessor
[09:17:31] [main/WARN] [mixin]: Error loading class: net/minecraft/client/renderer/EntityRenderer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:31] [main/WARN] [mixin]: @Mixin target net.minecraft.client.renderer.EntityRenderer was not found mixins.compat.shaders.replaymod.json:MixinShaderEntityRenderer
[09:17:31] [main/WARN] [mixin]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: The specified class 'shadersmod.client.ShadersRender' was not found)
[09:17:32] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[09:17:32] [main/WARN] [mixin]: Error loading class: net/minecraft/world/World (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:32] [main/WARN] [mixin]: Error loading class: net/minecraft/world/World (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:32] [main/WARN] [mixin]: Error loading class: net/minecraft/world/World (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:32] [main/WARN] [mixin]: Error loading class: net/minecraft/world/World (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:32] [main/WARN] [mixin]: Error loading class: net/minecraft/world/World (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@44b21f9f from coremod Chiseled Me ASM)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.world.World
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:741)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.client.main.Main.main(SourceFile:38)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[09:17:32] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[09:17:32] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[replaymod-1.12.2-2.3.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.world.World
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:741) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[replaymod-1.12.2-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[replaymod-1.12.2-2.3.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:17:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[09:17:32] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[09:17:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:17:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:17:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[09:17:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
```
</details>

**Comment by necauqua** [comment]
Looks like shadersmod and/or replaymod (thats what I can read from the log) are not compatible with this mod either, so we'll wait for ongoing mod rewrite to complete to find out if it helps with the issue.

**Comment by TheEggi98** [comment]
I also cant play with this mod atm. the Exception thrown even before the MC Loadingscreen shows up
My Log: https://paste.myftb.de/ikocewobek
From what i guess from the log it crashes from missing classes in World? (damn i really need to learn Java too^^)
i put this mod in FTB Builders Paradise with some extramods, if wanted i can also post the mod-list.

**Comment by necauqua** [comment]
@TheEggi98 
This crash is already fixed (with a metric ton of other mod compat crashes), so wait for the next release (will be in a week or so) and you can try again

**Comment by necauqua** [comment]
@253488655422 @TheEggi98 Ok so this initial issue initially was just invalid, and both of your issues (that you made as comments and not separate issues) are either fixed or at least affected in the current unreleased code, so I am closing this issue and if you have problems after the release you can open new issues.
