### ISSUE TITLE
Minecraft crashing (No optifine, 1.12.2)

### ISSUE THREAD

**Issue by Jinsto-Nim-Alt** [necauqua/chiseled-me#63]
I've updated to the newest version of forge, i've re-installed the mod multiple times, switched versions, took away all of the other mods, and it STILL crashes. Here is the error:

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@39198a86 from coremod Chiseled Me ASM
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 16 more
Caused by: java.lang.IllegalStateException: Coremod failed!
Some patches were not applied to class EntityRenderer:
  transformer 'cameraView':
    method func_78479_a(FI)V:
      - <insert before INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>
      - <insert after INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>

	at dev.necauqua.mods.cm.asm.dsl.ASM.checkMisses(ASM.java:182)
	at dev.necauqua.mods.cm.asm.dsl.ASM.doTransform(ASM.java:129)
	at dev.necauqua.mods.cm.asm.Plugin.transform(Plugin.java:40)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 18 more

**Comment by Jinsto-Nim-Alt** [comment]
Fixed! Apparently I had a secret mod or something, I came back later and it works

But when I added all of my mods back, it turns out ichunutil doesn't work with it!
