### ISSUE TITLE
I placed the mod into the minecraft/mods/ and then I just started minecraft, it crashed on me and it's saying : "An unexpected issue occured  the game has crashed. We're sorry for the inconvenience"

### ISSUE THREAD

**Issue by wwe83** [necauqua/chiseled-me#92]
When I try to use this mod with mod *X* (and/or by doing some set of actions), the game crashes. 

If you know exactly with what mod *X* this mod crashed, please check that it was not already reported.

**Additional information:**
- crashlog file or gist: *required*
- `minecraft_profile_folder/logs/debug.log` file: *providing this is highly recommended*

**PLEASE REFRAIN FROM POSTING GIANT WALLS OF TEXT, USE ANY KIND OF PASTEBIN, GIST OR JUST A PLAIN TEXT FILE**

**Comment by necauqua** [comment]
Make sure you are using Minecraft 1.12.2, latest Forge, there are no other mods.
If there are other mods - list them, or at least just send that `.minecraft/logs/debug.log` file like the issue template that you didn't even read suggested you to do.

I cannot predict what you did wrong without you telling me what you did (or at least sending the log which is like an incomplete recording of what you did and how the game worked until crashing), this is a very basic concept most humans learn around the age of 4.

What I _can_ predict though, is both the fact that you placed the mod in the mods folder, because there are *no other options* for you to get a crash caused by the mod, and that the game says those sentenses about unexpected issue and so on, because it does say that *every time* when it crashes.

So you wrote _absolutely nothing_ useful other than you having a crash (by just creating a crash issue), well good luck to me trying to help you out I guess.

**Comment by wwwlde** [comment]
Hello, @necauqua !

Here is debug log for this issue. Same error occurs with latest build.

```
[18:14:30] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-87-core.jar)
  Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  Techguns Core (Techguns-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 2/13/21 6:14 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
        at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
        at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@659d72ca from coremod Chiseled Me ASM
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        ... 16 more
Caused by: java.lang.IllegalStateException: Coremod failed!
Some patches were not applied to class EntityRenderer:
  transformer 'cameraView':
    method func_78467_g(F)V:
      - <insert before DSTORE 10>
    method func_78479_a(FI)V:
      - <insert before INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>
      - <insert after INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>

        at dev.necauqua.mods.cm.asm.dsl.ASM.checkMisses(ASM.java:182)
        at dev.necauqua.mods.cm.asm.dsl.ASM.doTransform(ASM.java:129)
        at dev.necauqua.mods.cm.asm.Plugin.transform(Plugin.java:40)
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
        ... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
        at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_51, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 528859504 bytes (504 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
        JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseM
illis=50 -XX:G1HeapRegionSize=32M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.5.2854 30 mods loaded, 30 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State | ID                   | Version       | Source                                    | Signature                                |
        |:----- |:-------------------- |:------------- |:----------------------------------------- |:---------------------------------------- |
        | LC    | minecraft            | 1.12.2        | minecraft.jar                             | None                                     |
        | LC    | mcp                  | 9.42          | minecraft.jar                             | None                                     |
        | LC    | FML                  | 8.0.99.99     | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LC    | forge                | 14.23.5.2854  | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LC    | micdoodlecore        |               | minecraft.jar                             | None                                     |
        | LC    | techguns_core        | 1.12.2-1.0    | minecraft.jar                             | None                                     |
        | LC    | xujmod               | 2.0.7         | Cars_and_Engines_Mod_1.12.2.jar           | None                                     |
        | LC    | chiseled_me          | 2.0.0.0       | chiseled-me-1.12.2-2.0.0.0.jar            | c677c954974252994736eb15e855e1e6fc5a2e62 |
        | LC    | moreexplosives       | 1.0.2         | Even_More_Explosives_Mod_1.12.2.jar       | None                                     |
        | LC    | motnt                | 1.0.1         | EvenMoreTNT-1.0.1.jar                     | None                                     |
        | LC    | farlanders           | 1.0.1         | Farlanders-Mod-1.12.2.jar                 | None                                     |
        | LC    | flansmod             | 5.5.2         | Flan's Mod-1.12.2-5.5.2.jar               | None                                     |
        | L     | flansmodapocalypse   | 1.0           | Flan's Mod-1.12.2-5.5.2.jar               | None                                     |
        | L     | ic2                  | 2.8.182-ex112 | industrialcraft_2_2.8.182_ex112.jar       | None                                     |
        | L     | galacticraftcore     | 4.0.2.244     | GalacticraftCore-1.12.2-4.0.2.244.jar     | None                                     |
        | L     | galacticraftplanets  | 4.0.2.244     | Galacticraft-Planets-1.12.2-4.0.2.244.jar | None                                     |
        | L     | giant_swords_mod     | 1.0.0         | GiantSwordsMod.jar                        | None                                     |
        | L     | ichunutil            | 7.2.2         | iChunUtil-1.12.2-7.2.2.jar                | None                                     |
        | L     | trackapi             | 1.2           | TrackAPI-1.2.jar                          | None                                     |
        | L     | immersiverailroading | 1.7.3         | ImmersiveRailroading-1.7.3_1.12.2.jar     | None                                     |
        | L     | universalmodcore     | 1.0.0         | ImmersiveRailroading-1.7.3_1.12.2.jar     | None                                     |
        | L     | lucky                | 7.5.0         | LuckyBlock_1_12_v7_5_0.zip                | None                                     |
        | L     | mymod                | 2.2           | Mechanicraft v2.2.jar                     | None                                     |
        | L     | mob_mash             | 2.4           | Mob-Mash-Mod-1.12.2.jar                   | None                                     |
        | L     | moreplayermodels     | 1.12.2        | MorePlayerModels_1.12.2(14nov17).jar      | None                                     |
        | L     | personalcars         | 1.4           | PersonalCars_1.12.1_1.4.jar               | None                                     |
        | L     | portalgun            | 7.1.0         | PortalGun_1.12.2_7.1.0.jar                | None                                     |
        | L     | techguns             | 2.0.2.0       | Techguns-Mod-1.12.2.jar                   | None                                     |
        | L     | xplosives            | 1.1           | xplosives-1.1.jar                         | None                                     |
        | L     | immersiveengineering | 0.12-87       | ImmersiveEngineering_0.12_87.jar          | None                                     |
        Loaded coremods (and transformers):
IELoadingPlugin (ImmersiveEngineering-0.12-87-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.0.jar)
  dev.necauqua.mods.cm.asm.Plugin
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
Techguns Core (Techguns-Mod-1.12.2.jar)
  techguns.core.TechgunsASMTransformer
        GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.16 27.20.1016.1' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
        Launched Version: 1.12.2-forge-14.23.5.2854
        LWJGL: 2.9.4
        OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.16 27.20.1016.1, ATI Technologies Inc.
        GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[18:14:30] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Vladislav\AppData\Roaming\.minecraft\crash-reports\crash-2021-02-13_18.14.
30-client.txt
```

**Comment by necauqua** [comment]
> Same error occurs with latest build

> Caused by: java.lang.IllegalStateException: Coremod failed!

This error cannot physically occur in the latest build, because the latest build is the beta from Discord, version `1.12-3.0.0.0-git-3af10ac`).
The code no longer throws such errors, so please try again by using said beta, the curse release is >1 years old and contains several severe mod compat issues causing it to crash with a lot of mods. They all (well, known ones) are fixed in that beta.

And yes it is very soon to be actually released on curse as a full-blown release, making finishing touches

**Comment by wwwlde** [comment]
Hi, @necauqua!

Oh sorry for misunderstanding! By the latest build i mean version `2.0.0.1`. Can you please provide link to `1.12-3.0.0.0-git-3af10ac`?

Thanks in advance!

Here is crash log for version 2.0.0.1:

```
[21:23:14] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-87-core.jar)
  Chiseled Me ASM (chiseled_me_1.12.2_2.0.0.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  Techguns Core (Techguns-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 2/13/21 9:23 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
        at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
        at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@71165e41 from coremod Chiseled Me ASM
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        ... 16 more
Caused by: java.lang.IllegalStateException: Coremod failed!
Some patches were not applied to class EntityRenderer:
  transformer 'cameraView':
    method func_78479_a(FI)V:
      - <insert before INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>
      - <insert after INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>

        at dev.necauqua.mods.cm.asm.dsl.ASM.checkMisses(ASM.java:182)
        at dev.necauqua.mods.cm.asm.dsl.ASM.doTransform(ASM.java:129)
        at dev.necauqua.mods.cm.asm.Plugin.transform(Plugin.java:40)
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
        ... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
        at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
        at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
        at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_51, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 320535704 bytes (305 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
        JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseM
illis=50 -XX:G1HeapRegionSize=32M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.5.2854 30 mods loaded, 30 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State | ID                   | Version       | Source                                    | Signature                                |
        |:----- |:-------------------- |:------------- |:----------------------------------------- |:---------------------------------------- |
        | LC    | minecraft            | 1.12.2        | minecraft.jar                             | None                                     |
        | LC    | mcp                  | 9.42          | minecraft.jar                             | None                                     |
        | LC    | FML                  | 8.0.99.99     | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LC    | forge                | 14.23.5.2854  | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LC    | micdoodlecore        |               | minecraft.jar                             | None                                     |
        | LC    | techguns_core        | 1.12.2-1.0    | minecraft.jar                             | None                                     |
        | LC    | xujmod               | 2.0.7         | Cars_and_Engines_Mod_1.12.2.jar           | None                                     |
        | LC    | chiseled_me          | 2.0.0.1       | chiseled_me_1.12.2_2.0.0.1.jar            | c677c954974252994736eb15e855e1e6fc5a2e62 |
        | LC    | moreexplosives       | 1.0.2         | Even_More_Explosives_Mod_1.12.2.jar       | None                                     |
        | LC    | motnt                | 1.0.1         | EvenMoreTNT-1.0.1.jar                     | None                                     |
        | LC    | farlanders           | 1.0.1         | Farlanders-Mod-1.12.2.jar                 | None                                     |
        | LC    | flansmod             | 5.5.2         | Flan's Mod-1.12.2-5.5.2.jar               | None                                     |
        | LC    | flansmodapocalypse   | 1.0           | Flan's Mod-1.12.2-5.5.2.jar               | None                                     |
        | LC    | ic2                  | 2.8.182-ex112 | industrialcraft_2_2.8.182_ex112.jar       | de041f9f6187debbc77034a344134053277aa3b0 |
        | LC    | galacticraftcore     | 4.0.2.244     | GalacticraftCore-1.12.2-4.0.2.244.jar     | None                                     |
        | LC    | galacticraftplanets  | 4.0.2.244     | Galacticraft-Planets-1.12.2-4.0.2.244.jar | None                                     |
        | LC    | giant_swords_mod     | 1.0.0         | GiantSwordsMod.jar                        | None                                     |
        | LC    | ichunutil            | 7.2.2         | iChunUtil-1.12.2-7.2.2.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
        | LC    | trackapi             | 1.2           | TrackAPI-1.2.jar                          | None                                     |
        | LC    | immersiverailroading | 1.7.3         | ImmersiveRailroading-1.7.3_1.12.2.jar     | None                                     |
        | LC    | universalmodcore     | 1.0.0         | ImmersiveRailroading-1.7.3_1.12.2.jar     | None                                     |
        | LC    | lucky                | 7.5.0         | LuckyBlock_1_12_v7_5_0.zip                | None                                     |
        | LC    | mymod                | 2.2           | Mechanicraft v2.2.jar                     | None                                     |
        | LC    | mob_mash             | 2.4           | Mob-Mash-Mod-1.12.2.jar                   | None                                     |
        | LC    | moreplayermodels     | 1.12.2        | MorePlayerModels_1.12.2(14nov17).jar      | None                                     |
        | LC    | personalcars         | 1.4           | PersonalCars_1.12.1_1.4.jar               | None                                     |
        | LC    | portalgun            | 7.1.0         | PortalGun_1.12.2_7.1.0.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
        | LC    | techguns             | 2.0.2.0       | Techguns-Mod-1.12.2.jar                   | None                                     |
        | LC    | xplosives            | 1.1           | xplosives-1.1.jar                         | None                                     |
        | LC    | immersiveengineering | 0.12-87       | ImmersiveEngineering_0.12_87.jar          | 4cb49fcde3b43048c9889e0a3d083225da926334 |
        Loaded coremods (and transformers):
IELoadingPlugin (ImmersiveEngineering-0.12-87-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Chiseled Me ASM (chiseled_me_1.12.2_2.0.0.1.jar)
  dev.necauqua.mods.cm.asm.Plugin
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
Techguns Core (Techguns-Mod-1.12.2.jar)
  techguns.core.TechgunsASMTransformer
        GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.16 27.20.1016.1' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
        Launched Version: 1.12.2-forge-14.23.5.2854
        LWJGL: 2.9.4
        OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.16 27.20.1016.1, ATI Technologies Inc.
        GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[21:23:14] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Vladislav\AppData\Roaming\.minecraft\crash-reports\crash-2021-02-13_21.23.
14-client.txt
```

**Comment by GiantLuigi4** [comment]
link to 1.12-3.0.0.0-git-3af10ac: https://cdn.discordapp.com/attachments/708757460890026086/806578264238719066/chiseled-me-1.12-3.0.0.0-git-3af10ac.jar

**Comment by wwwlde** [comment]
> link to 1.12-3.0.0.0-git-3af10ac: https://cdn.discordapp.com/attachments/708757460890026086/806578264238719066/chiseled-me-1.12-3.0.0.0-git-3af10ac.jar

Thanks!

**Comment by necauqua** [comment]
closing because no info and likely reporter has no issues after upgrading to git version
